name: Pull Request Comment Flow

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  comment-bot:
    name: Comment Bot
    runs-on: ubuntu-latest
    steps:
      - name: Check comments
        uses: khan/pull-request-comment-trigger@bb03972cc9f423111f3b5a23fcc9fd32741acabb
        id: check
        with:
          trigger: '#snapshot/update'
          prefix_only: true
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo "${TRIGGERED}:$COMMENT_BODY"'
        env:
          COMMENT_BODY: '${{ github.event.comment.body }}'
          TRIGGERED: '${{ steps.check.outputs.triggered }}'
      - run: |
          echo "ref: $GITHUB_REF"
          echo "head ref: $GITHUB_HEAD_REF"
          echo "base ref: $GITHUB_BASE_REF"
      - uses: actions/checkout@v2
        if: steps.check.outputs.triggered == 'true'
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch -v
          echo "$COMMENT_BODY" | grep -qe '^develop$' && scripts/update-snapshot --opam snapshot-develop.opam || true
          echo "$COMMENT_BODY" | grep -qe '^stable 0\.0\.4$' && scripts/update-snapshot --opam snapshot-stable-0-0-4.opam || true
          echo "$COMMENT_BODY" | grep -qe '^stable 0\.0\.5$' && scripts/update-snapshot --opam snapshot-stable-0-0-5.opam || true
          git add snapshot-*.opam
          git commit -m "Update snapshots" || echo "No files to commit"
          git push
        if: steps.check.outputs.triggered == 'true'
        env:
          COMMENT_BODY: '${{ github.event.comment.body }}'
