name: Pull Request Comment Flow

on: []
#  pull_request:
#    types: [opened]
#  issue_comment:
#    types: [created]

jobs:
  comment-bot:
    name: Comment Bot
    runs-on: ubuntu-latest
    steps:
      - name: Check comments
        uses: khan/pull-request-comment-trigger@bb03972cc9f423111f3b5a23fcc9fd32741acabb
        id: check
        with:
          trigger: '#snapshot/update'
          prefix_only: true
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - uses: actions/github-script@v2
        id: head-branch
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return {
              ref: pull_request.data.head.ref,
              repo: pull_request.data.head.repo.full_name
            };

      - run: |
          echo "ref: $GITHUB_REF"
          echo "upstream ref: $HEAD_REF"
          echo "head repo: $HEAD_REPO"
        env:
          HEAD_REF: ${{ steps.head-branch.outputs.result.ref }}
          HEAD_REPO: ${{ steps.head-branch.outputs.result.repo }}
      - uses: actions/checkout@v2
        if: steps.check.outputs.triggered == 'true'
        with:
          fetch-depth: 0
          ref: ${{ steps.upstreambranch.outputs.branchname }}
      - name: Update snapshots
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch -v
          git remote -v
          echo "$COMMENT_BODY" | grep -qe '^develop$' && scripts/update-snapshot --opam snapshot-develop.opam || true
          echo "$COMMENT_BODY" | grep -qe '^stable 0\.0\.4$' && scripts/update-snapshot --opam snapshot-stable-0-0-4.opam || true
          echo "$COMMENT_BODY" | grep -qe '^stable 0\.0\.5$' && scripts/update-snapshot --opam snapshot-stable-0-0-5.opam || true
          git add snapshot-*.opam
          git commit -m "Update snapshots" || echo "No files to commit"
          git push
        if: steps.check.outputs.triggered == 'true'
        env:
          COMMENT_BODY: '${{ github.event.comment.body }}'
