name: Pull Request Follow-Up Flow

on:
 pull_request:
   types: [closed]

jobs:
  follow-up:
    name: Pull Request Follow-Up
    runs-on: ubuntu-latest
    steps:

      - uses: actions/github-script@v2
        id: head-branch
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return {
              ref: pull_request.data.head.ref,
              repo: pull_request.data.head.repo.full_name,
              body: pull_request.data.body.replace(/\r?\n/g, '\n')
            };

      - run: |
          echo "ref: $GITHUB_REF"
          echo "upstream ref: $RESULT"
          echo "head repo: $HEAD_REPO"
        env:
          PR: ${{ steps.head-branch.outputs.result }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update snapshots
        run: |
          git branch -v
          git remote -v
          echo "$PR" | jq -r '.body' | sed -e '/^- \[[xX]\] Add to snapshot /!d' -e 's!^[^`]*`!!' -e 's!`:!.opam!' -e '/^[-+. [:alnum:]]*$/!d' | xargs -L1 scripts/update-snapshot --opam
        env:
          PR: ${{ steps.head-branch.outputs.result }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
#          token: ${{ secrets.REPO_PUBLIC }}
          commit-message: Take snapshots
          branch: 'update-snapshots-${{ github.event.pull_request.number }}'
          title: '[Automated] Follow up #${{ github.event.pull_request.number }}'
          body: |
            Follow up #${{ github.event.pull_request.number }}
          labels: |
            automated pr
#          assignees: na4zagin3
#          reviewers: na4zagin3
          team-reviewers: |
            owners
            maintainers
