name: Pull Request Flow

on:
  pull_request_target:
    types: [opened, reopened]
# tags-ignore and/or paths does not work with pull_request_target
#    tags-ignore:
#      - "automated pr"
#    paths:
#      - "packages/**"

jobs:
  notify:
    name: Notify snapshot update
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: actions/github-script@v2
        env:
          HEAD_BRANCH: ${{ github.head_ref }}
          GITHUB_ACTOR: ${{ github.actor }}
        with:
          github-token: ${{ github.token }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
            🎉🎉🎉 Thank you for sending a PR!

            If this PR is to add new or updated SATySFi libraries, I would like you to include your new library in the package snapshots, by following the instructions below.

            Please leave a comment in case you don't want to add your libraries to the package snapshots.

            First, clone your fork of this repository.

            \`\`\`
            $ git clone https://github.com/na4zagin3/${context.repo.repo}.git
            $ cd ${context.repo.repo}
            $ git remote add ${process.env.GITHUB_ACTOR} https://github.com/${process.env.GITHUB_ACTOR}/${context.repo.repo}.git
            \`\`\`
            
            Checkout your branch.
            
            \`\`\`
            $ git fetch ${process.env.GITHUB_ACTOR}
            $ git checkout -b ${process.env.HEAD_BRANCH}  ${process.env.GITHUB_ACTOR}/${process.env.HEAD_BRANCH} 
            \`\`\`

            - (Recommended) If your library supports the latest SATySFi 0.0.5 develop version (and the next stable version), run

              \`\`\`
              $ scripts/update-snapshot --opam snapshot-develop.opam
              \`\`\`

            - (Recommended) If your library supports SATySFi 0.0.5, run

              \`\`\`
              $ scripts/update-snapshot --opam snapshot-stable-0-0-5.opam
              \`\`\`

            - If your library supports SATySFi 0.0.4, run

              \`\`\`
              $ scripts/update-snapshot --opam snapshot-stable-0-0-4.opam
              \`\`\`

            **Notes:** I recommend adding your libraries to the snapshot with the latest develop version as well
            if your library supports the latest stable version,
            because the snapshot with the latest develop version will be the snapshot with the the comming SATySFi stable version.
            
            Finally, commit the change and push it.

            \`\`\`
            $ git add snapshot-*.opam
            $ git commit -m 'Update snapshots'
            $ git push
            \`\`\`

            Thanks!
            `
            })
